apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: webapp-namespace
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 782879222248.dkr.ecr.us-east-1.amazonaws.com/assignment2:webapp-v0.1 
    env:
    - name: DBHOST
      value: "10.244.0.5"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: root
    - name: DBPWD
      value: pw
    - name: DATABASE
      value: employees
    - name: APP_COLOR
      value: blue
    ports:
    - containerPort: 8080
